In [32]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/student-performance-multiple-linear-regression/Student_Performance.csv

In [33]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/kaggle/input/student-performance-multiple-linear-regression/Student_Performance.csv')
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [ ]:
df.describe()

In [ ]:
df = df.drop(['Extracurricular Activities'], axis = 1)
df

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
fig = px.scatter_3d(df, x = 'Hours Studied', y = 'Previous Scores', z = 'Performance Index')
fig.show()

In [ ]:
fig2 = px.scatter_3d(df, x = 'Sleep Hours', y = 'Sample Question Papers Practiced', z = 'Performance Index')
fig2.show()

In [ ]:
fig3 = px.scatter_3d(df, x = 'Hours Studied', y = 'Sleep Hours', z = 'Performance Index')
fig3.show()

In [ ]:
df

In [ ]:
x = df.iloc[:, 0:4]
x

In [ ]:
y = df.iloc[:,-1]
y

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)
x_test

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [47]:
model.fit(x_train,y_train)

LinearRegression()

In [48]:
y_pred = model.predict(x_test)
y_pred

array([55.00786377, 22.31444624, 47.59404705, ..., 16.48182916,
       63.64243731, 46.23799491])

In [ ]:
y_test

In [ ]:
print('beta0 = ', model.intercept_)
print('beta_values = ', model.coef_)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mae = mean_absolute_error(y_test,y_pred)
print(mae)

In [ ]:
mse = mean_squared_error(y_test,y_pred)
print(mse)

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
print(rmse)

In [ ]:
r2 = r2_score(y_test,y_pred)
print(r2)

In [ ]:
adjusted_r2 = (1- ((1-r2)*(2000 - 1)/(2000-4-1)))
print(adjusted_r2)

# Custom Multiple linear regression function

In [ ]:
class Multiple_Linear_Regression:
    
    def __init__(self):
        self.intercept_ = None
        self.coef_ = None 

    def fit(self,x_train,y_train):
        x_train = np.insert(x_train,0, 1, axis = 1)  #for introducing intercept term in the data


        #beta = ((inverse of ((transpose of x)*x)) * (transpose of x)*(y))
        beta = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train) #formula for finding beta values(first value will be intercept and rest are the coefficient)
        self.intercept_ = beta[0]
        self.coef_ = beta[1:]

    def predict(self,x_test):
        y_pred = np.dot(x_test,self.coef_) + self.intercept_
        return y_pred

In [ ]:
mlr = Multiple_Linear_Regression()

In [ ]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

In [ ]:
mlr.fit(x_train,y_train)

In [ ]:
y_pred = mlr.predict(x_test)

In [ ]:
r2_score(y_test,y_pred)